# Generated by Django 4.1.5 on 2023-01-23 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_answer_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='careercategory',
            name='image',
            field=models.ImageField(null=True, upload_to='images/%Y/%m'),
        ),
    ]
