# Generated by Django 4.1.5 on 2023-01-27 12:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_user_day_of_birth_alter_answer_career_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finished_time', models.DateTimeField(auto_now_add=True)),
                ('career_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.careercategory')),
                ('participant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
