# Generated by Django 4.1.5 on 2023-01-27 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_survey'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='survey',
            options={'ordering': ['id']},
        ),
    ]
