# Generated by Django 4.1.5 on 2023-01-27 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_alter_survey_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='survey',
            old_name='finished_time',
            new_name='created_date',
        ),
    ]
