# Generated by Django 4.1.5 on 2023-01-28 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_rename_finished_time_survey_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='career_category',
            field=models.TextField(blank=True, null=True),
        ),
    ]
