# Generated by Django 4.1.5 on 2023-01-28 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_alter_survey_career_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='career_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.careercategory'),
        ),
    ]
