# Generated by Django 4.1.5 on 2023-01-28 05:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_remove_survey_career_category_survey_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='participant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
