# Generated by Django 4.1.5 on 2023-02-06 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_alter_survey_result'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='survey',
            options={'ordering': ['-id']},
        ),
    ]
