# Generated by Django 4.1.5 on 2023-02-10 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0018_alter_survey_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Universitie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('universiti_name', models.TextField()),
                ('universiti_link', models.TextField()),
            ],
        ),
    ]
