# Generated by Django 4.1.5 on 2023-02-13 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0023_careercategory_detail_alter_feedback_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(null=True, upload_to='uploads/user/%Y/%m'),
        ),
    ]
